# Generated by Django 5.1.5 on 2025-01-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('average_salary_rub', models.FloatField()),
                ('total_vacancies', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('average_salary_rub', models.FloatField()),
                ('total_vacancies', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profession_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=200)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GeographyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('average_salary_rub', models.FloatField()),
                ('vacancies_share', models.FloatField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profession')),
            ],
        ),
        migrations.CreateModel(
            name='DemandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('average_salary_rub', models.FloatField()),
                ('total_vacancies', models.PositiveIntegerField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profession')),
            ],
        ),
        migrations.CreateModel(
            name='SkillByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('frequency', models.PositiveIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_years', to='api.skill')),
            ],
        ),
    ]
